[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@11.2.2",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
